import os
import json
import asyncio 
from flask import Flask, request, jsonify
from dotenv import load_dotenv

from google.adk.agents import Agent 
from google.adk.runners import InMemoryRunner
from google.genai import types

# Load environment variables from your .env file
load_dotenv()

app = Flask(__name__)

# 1. Define the Agent's Core Instructions
SYSTEM_PROMPT = """
You are the PhishGuard Zero-Trust text analyzer. 
Your only job is to analyze incoming messages for social engineering tactics, urgency triggers, and phishing attempts.
You must return ONLY a valid JSON object with no markdown formatting. The JSON must contain exactly two keys:
1. "Threat_Level": Choose "Low", "Medium", or "High".
2. "Red_Flag_Summary": A one-sentence explanation of the psychological manipulation used (or "No obvious manipulation detected" if safe).
"""

# 2. Initialize the ADK Agent
agent = Agent(
    name="phishguard_api_agent",
    model="gemini-2.5-flash",
    instruction=SYSTEM_PROMPT
)

# 3. Define the Web Endpoint
@app.route('/analyze', methods=['POST'])
def analyze_text():
    data = request.get_json()
    if not data or 'message' not in data:
        return jsonify({"error": "Invalid request. Please provide a JSON payload with a 'message' key."}), 400
    
    user_message = data['message']
    
    try:
        # Create the temporary runner and explicitly assign an app_name
        local_runner = InMemoryRunner(agent=agent, app_name="phishguard_app")
        
        # Use session_service and asyncio to properly generate the session
        session = asyncio.run(local_runner.session_service.create_session(
            app_name="phishguard_app",
            user_id="api_user"
        ))
        
        final_text = ""
        
        # Format the user message safely for the ADK
        content = types.Content(role='user', parts=[types.Part.from_text(text=user_message)])
        
        # Pass the exact session.id generated by the service
        for event in local_runner.run(user_id="api_user", session_id=session.id, new_message=content):
            if event.is_final_response():
                if hasattr(event, 'content') and event.content and event.content.parts:
                    final_text = event.content.parts[0].text
                elif hasattr(event, 'text'):  
                    final_text = event.text
        
        # Clean the response to ensure it is strict JSON
        clean_text = final_text.strip().strip('```json').strip('```')
        result_dict = json.loads(clean_text)
        
        return jsonify(result_dict), 200

    except Exception as e:
        return jsonify({"error": f"Failed to process the message: {str(e)}"}), 500
    
# 4. Web Interface Route (Dark Mode + Pretty Formatting)
@app.route('/', methods=['GET'])
def index():
    html_content = """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>PhishGuard | Dark Edition</title>
        <style>
            body { 
                font-family: 'Inter', -apple-system, sans-serif; 
                max-width: 700px; 
                margin: 0 auto; 
                padding: 40px 20px; 
                background-color: #0d1117; 
                color: #c9d1d9; 
            }
            .container {
                background-color: #161b22;
                padding: 30px;
                border-radius: 12px;
                border: 1px solid #30363d;
                box-shadow: 0 10px 30px rgba(0,0,0,0.5);
            }
            h2 { color: #58a6ff; margin-top: 0; display: flex; align-items: center; gap: 10px; }
            p { color: #8b949e; }
            textarea { 
                width: 100%; 
                height: 150px; 
                margin-top: 15px;
                padding: 15px; 
                background-color: #0d1117;
                color: #e6edf3;
                border: 1px solid #30363d; 
                border-radius: 8px; 
                font-family: inherit;
                resize: vertical;
                box-sizing: border-box;
            }
            textarea:focus { outline: none; border-color: #58a6ff; }
            .controls { margin-top: 20px; display: flex; justify-content: flex-end; }
            button { 
                padding: 12px 28px; 
                background-color: #238636; 
                color: white; 
                border: none; 
                border-radius: 6px; 
                cursor: pointer; 
                font-weight: 600;
                transition: background 0.2s;
            }
            button:hover { background-color: #2ea043; }
            
            #resultWrapper { 
                margin-top: 30px; 
                display: none; /* Hidden until first scan */
                padding: 20px;
                border-radius: 8px;
                background-color: #21262d;
            }
            .label { font-size: 0.8rem; text-transform: uppercase; color: #8b949e; letter-spacing: 1px; }
            .value { font-size: 1.1rem; margin: 5px 0 15px 0; font-weight: 500; }
            
            /* Threat Level Colors */
            .level-high { color: #ff7b72; font-weight: bold; }
            .level-medium { color: #d29922; font-weight: bold; }
            .level-low { color: #3fb950; font-weight: bold; }
        </style>
    </head>
    <body>
        <div class="container">
            <h2>🛡️ PhishGuard API</h2>
            <p>Paste the content of a suspicious email or message below to evaluate security risks in real-time.</p>
            
            <textarea id="messageInput" placeholder="Enter message text here..."></textarea>
            
            <div class="controls">
                <button id="scanBtn" onclick="analyzeMessage()">Scan for Threats</button>
            </div>

            <div id="resultWrapper">
                <div class="label">Threat Level Assessment</div>
                <div id="riskLevel" class="value">--</div>
                
                <div class="label">AI Security Summary</div>
                <div id="summaryText" class="value" style="color: #e6edf3;">--</div>
            </div>
        </div>

        <script>
            async function analyzeMessage() {
                const message = document.getElementById('messageInput').value;
                const scanBtn = document.getElementById('scanBtn');
                const resultWrapper = document.getElementById('resultWrapper');
                
                if(!message.trim()) return alert("Please enter a message first.");

                // UI Feedback
                scanBtn.innerText = "Analyzing...";
                scanBtn.disabled = true;

                try {
                    const response = await fetch('/analyze', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify({ message: message })
                    });
                    const data = await response.json();
                    
                    // Show results area
                    resultWrapper.style.display = "block";
                    
                    // Update Risk Level with Dynamic Color
                    const riskEl = document.getElementById('riskLevel');
                    const level = data.Threat_Level || "Unknown";
                    riskEl.innerText = level;
                    riskEl.className = "value level-" + level.toLowerCase();
                    
                    // Update Summary
                    document.getElementById('summaryText').innerText = data.Red_Flag_Summary || "No summary available.";

                } catch (error) {
                    alert("Analysis failed. The model might be busy. Try again in a few seconds.");
                } finally {
                    scanBtn.innerText = "Scan for Threats";
                    scanBtn.disabled = false;
                }
            }
        </script>
    </body>
    </html>
    """
    return html_content

# 5. Health Check Route
@app.route('/', methods=['GET'])
def health_check():
    return "PhishGuard API is running! Send POST requests to /analyze"

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 8080))
    app.run(debug=True, use_reloader=False, host='0.0.0.0', port=port)